# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pc24/lyricstator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pc24/lyricstator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc24/lyricstator/CMakeFiles /home/pc24/lyricstator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc24/lyricstator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lyricstator

# Build rule for target.
Lyricstator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lyricstator
.PHONY : Lyricstator

# fast build rule for target.
Lyricstator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/build
.PHONY : Lyricstator/fast

src/ai/NoteDetector.o: src/ai/NoteDetector.cpp.o
.PHONY : src/ai/NoteDetector.o

# target to build an object file
src/ai/NoteDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/ai/NoteDetector.cpp.o
.PHONY : src/ai/NoteDetector.cpp.o

src/ai/NoteDetector.i: src/ai/NoteDetector.cpp.i
.PHONY : src/ai/NoteDetector.i

# target to preprocess a source file
src/ai/NoteDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/ai/NoteDetector.cpp.i
.PHONY : src/ai/NoteDetector.cpp.i

src/ai/NoteDetector.s: src/ai/NoteDetector.cpp.s
.PHONY : src/ai/NoteDetector.s

# target to generate assembly for a file
src/ai/NoteDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/ai/NoteDetector.cpp.s
.PHONY : src/ai/NoteDetector.cpp.s

src/audio/AudioManager.o: src/audio/AudioManager.cpp.o
.PHONY : src/audio/AudioManager.o

# target to build an object file
src/audio/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/AudioManager.cpp.o
.PHONY : src/audio/AudioManager.cpp.o

src/audio/AudioManager.i: src/audio/AudioManager.cpp.i
.PHONY : src/audio/AudioManager.i

# target to preprocess a source file
src/audio/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/AudioManager.cpp.i
.PHONY : src/audio/AudioManager.cpp.i

src/audio/AudioManager.s: src/audio/AudioManager.cpp.s
.PHONY : src/audio/AudioManager.s

# target to generate assembly for a file
src/audio/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/AudioManager.cpp.s
.PHONY : src/audio/AudioManager.cpp.s

src/audio/MidiParser.o: src/audio/MidiParser.cpp.o
.PHONY : src/audio/MidiParser.o

# target to build an object file
src/audio/MidiParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/MidiParser.cpp.o
.PHONY : src/audio/MidiParser.cpp.o

src/audio/MidiParser.i: src/audio/MidiParser.cpp.i
.PHONY : src/audio/MidiParser.i

# target to preprocess a source file
src/audio/MidiParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/MidiParser.cpp.i
.PHONY : src/audio/MidiParser.cpp.i

src/audio/MidiParser.s: src/audio/MidiParser.cpp.s
.PHONY : src/audio/MidiParser.s

# target to generate assembly for a file
src/audio/MidiParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/audio/MidiParser.cpp.s
.PHONY : src/audio/MidiParser.cpp.s

src/core/Application.o: src/core/Application.cpp.o
.PHONY : src/core/Application.o

# target to build an object file
src/core/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/core/Application.cpp.o
.PHONY : src/core/Application.cpp.o

src/core/Application.i: src/core/Application.cpp.i
.PHONY : src/core/Application.i

# target to preprocess a source file
src/core/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/core/Application.cpp.i
.PHONY : src/core/Application.cpp.i

src/core/Application.s: src/core/Application.cpp.s
.PHONY : src/core/Application.s

# target to generate assembly for a file
src/core/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/core/Application.cpp.s
.PHONY : src/core/Application.cpp.s

src/export/FormatExporter.o: src/export/FormatExporter.cpp.o
.PHONY : src/export/FormatExporter.o

# target to build an object file
src/export/FormatExporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/export/FormatExporter.cpp.o
.PHONY : src/export/FormatExporter.cpp.o

src/export/FormatExporter.i: src/export/FormatExporter.cpp.i
.PHONY : src/export/FormatExporter.i

# target to preprocess a source file
src/export/FormatExporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/export/FormatExporter.cpp.i
.PHONY : src/export/FormatExporter.cpp.i

src/export/FormatExporter.s: src/export/FormatExporter.cpp.s
.PHONY : src/export/FormatExporter.s

# target to generate assembly for a file
src/export/FormatExporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/export/FormatExporter.cpp.s
.PHONY : src/export/FormatExporter.cpp.s

src/gui/KaraokeDisplay.o: src/gui/KaraokeDisplay.cpp.o
.PHONY : src/gui/KaraokeDisplay.o

# target to build an object file
src/gui/KaraokeDisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/KaraokeDisplay.cpp.o
.PHONY : src/gui/KaraokeDisplay.cpp.o

src/gui/KaraokeDisplay.i: src/gui/KaraokeDisplay.cpp.i
.PHONY : src/gui/KaraokeDisplay.i

# target to preprocess a source file
src/gui/KaraokeDisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/KaraokeDisplay.cpp.i
.PHONY : src/gui/KaraokeDisplay.cpp.i

src/gui/KaraokeDisplay.s: src/gui/KaraokeDisplay.cpp.s
.PHONY : src/gui/KaraokeDisplay.s

# target to generate assembly for a file
src/gui/KaraokeDisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/KaraokeDisplay.cpp.s
.PHONY : src/gui/KaraokeDisplay.cpp.s

src/gui/UserInterface.o: src/gui/UserInterface.cpp.o
.PHONY : src/gui/UserInterface.o

# target to build an object file
src/gui/UserInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/UserInterface.cpp.o
.PHONY : src/gui/UserInterface.cpp.o

src/gui/UserInterface.i: src/gui/UserInterface.cpp.i
.PHONY : src/gui/UserInterface.i

# target to preprocess a source file
src/gui/UserInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/UserInterface.cpp.i
.PHONY : src/gui/UserInterface.cpp.i

src/gui/UserInterface.s: src/gui/UserInterface.cpp.s
.PHONY : src/gui/UserInterface.s

# target to generate assembly for a file
src/gui/UserInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/UserInterface.cpp.s
.PHONY : src/gui/UserInterface.cpp.s

src/gui/Window.o: src/gui/Window.cpp.o
.PHONY : src/gui/Window.o

# target to build an object file
src/gui/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/Window.cpp.o
.PHONY : src/gui/Window.cpp.o

src/gui/Window.i: src/gui/Window.cpp.i
.PHONY : src/gui/Window.i

# target to preprocess a source file
src/gui/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/Window.cpp.i
.PHONY : src/gui/Window.cpp.i

src/gui/Window.s: src/gui/Window.cpp.s
.PHONY : src/gui/Window.s

# target to generate assembly for a file
src/gui/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/gui/Window.cpp.s
.PHONY : src/gui/Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scripting/LystrInterpreter.o: src/scripting/LystrInterpreter.cpp.o
.PHONY : src/scripting/LystrInterpreter.o

# target to build an object file
src/scripting/LystrInterpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrInterpreter.cpp.o
.PHONY : src/scripting/LystrInterpreter.cpp.o

src/scripting/LystrInterpreter.i: src/scripting/LystrInterpreter.cpp.i
.PHONY : src/scripting/LystrInterpreter.i

# target to preprocess a source file
src/scripting/LystrInterpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrInterpreter.cpp.i
.PHONY : src/scripting/LystrInterpreter.cpp.i

src/scripting/LystrInterpreter.s: src/scripting/LystrInterpreter.cpp.s
.PHONY : src/scripting/LystrInterpreter.s

# target to generate assembly for a file
src/scripting/LystrInterpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrInterpreter.cpp.s
.PHONY : src/scripting/LystrInterpreter.cpp.s

src/scripting/LystrParser.o: src/scripting/LystrParser.cpp.o
.PHONY : src/scripting/LystrParser.o

# target to build an object file
src/scripting/LystrParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrParser.cpp.o
.PHONY : src/scripting/LystrParser.cpp.o

src/scripting/LystrParser.i: src/scripting/LystrParser.cpp.i
.PHONY : src/scripting/LystrParser.i

# target to preprocess a source file
src/scripting/LystrParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrParser.cpp.i
.PHONY : src/scripting/LystrParser.cpp.i

src/scripting/LystrParser.s: src/scripting/LystrParser.cpp.s
.PHONY : src/scripting/LystrParser.s

# target to generate assembly for a file
src/scripting/LystrParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/scripting/LystrParser.cpp.s
.PHONY : src/scripting/LystrParser.cpp.s

src/sync/SynchronizationManager.o: src/sync/SynchronizationManager.cpp.o
.PHONY : src/sync/SynchronizationManager.o

# target to build an object file
src/sync/SynchronizationManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/sync/SynchronizationManager.cpp.o
.PHONY : src/sync/SynchronizationManager.cpp.o

src/sync/SynchronizationManager.i: src/sync/SynchronizationManager.cpp.i
.PHONY : src/sync/SynchronizationManager.i

# target to preprocess a source file
src/sync/SynchronizationManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/sync/SynchronizationManager.cpp.i
.PHONY : src/sync/SynchronizationManager.cpp.i

src/sync/SynchronizationManager.s: src/sync/SynchronizationManager.cpp.s
.PHONY : src/sync/SynchronizationManager.s

# target to generate assembly for a file
src/sync/SynchronizationManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/sync/SynchronizationManager.cpp.s
.PHONY : src/sync/SynchronizationManager.cpp.s

src/utils/ErrorHandler.o: src/utils/ErrorHandler.cpp.o
.PHONY : src/utils/ErrorHandler.o

# target to build an object file
src/utils/ErrorHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/ErrorHandler.cpp.o
.PHONY : src/utils/ErrorHandler.cpp.o

src/utils/ErrorHandler.i: src/utils/ErrorHandler.cpp.i
.PHONY : src/utils/ErrorHandler.i

# target to preprocess a source file
src/utils/ErrorHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/ErrorHandler.cpp.i
.PHONY : src/utils/ErrorHandler.cpp.i

src/utils/ErrorHandler.s: src/utils/ErrorHandler.cpp.s
.PHONY : src/utils/ErrorHandler.s

# target to generate assembly for a file
src/utils/ErrorHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/ErrorHandler.cpp.s
.PHONY : src/utils/ErrorHandler.cpp.s

src/utils/FileUtils.o: src/utils/FileUtils.cpp.o
.PHONY : src/utils/FileUtils.o

# target to build an object file
src/utils/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/FileUtils.cpp.o
.PHONY : src/utils/FileUtils.cpp.o

src/utils/FileUtils.i: src/utils/FileUtils.cpp.i
.PHONY : src/utils/FileUtils.i

# target to preprocess a source file
src/utils/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/FileUtils.cpp.i
.PHONY : src/utils/FileUtils.cpp.i

src/utils/FileUtils.s: src/utils/FileUtils.cpp.s
.PHONY : src/utils/FileUtils.s

# target to generate assembly for a file
src/utils/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lyricstator.dir/build.make CMakeFiles/Lyricstator.dir/src/utils/FileUtils.cpp.s
.PHONY : src/utils/FileUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Lyricstator"
	@echo "... src/ai/NoteDetector.o"
	@echo "... src/ai/NoteDetector.i"
	@echo "... src/ai/NoteDetector.s"
	@echo "... src/audio/AudioManager.o"
	@echo "... src/audio/AudioManager.i"
	@echo "... src/audio/AudioManager.s"
	@echo "... src/audio/MidiParser.o"
	@echo "... src/audio/MidiParser.i"
	@echo "... src/audio/MidiParser.s"
	@echo "... src/core/Application.o"
	@echo "... src/core/Application.i"
	@echo "... src/core/Application.s"
	@echo "... src/export/FormatExporter.o"
	@echo "... src/export/FormatExporter.i"
	@echo "... src/export/FormatExporter.s"
	@echo "... src/gui/KaraokeDisplay.o"
	@echo "... src/gui/KaraokeDisplay.i"
	@echo "... src/gui/KaraokeDisplay.s"
	@echo "... src/gui/UserInterface.o"
	@echo "... src/gui/UserInterface.i"
	@echo "... src/gui/UserInterface.s"
	@echo "... src/gui/Window.o"
	@echo "... src/gui/Window.i"
	@echo "... src/gui/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scripting/LystrInterpreter.o"
	@echo "... src/scripting/LystrInterpreter.i"
	@echo "... src/scripting/LystrInterpreter.s"
	@echo "... src/scripting/LystrParser.o"
	@echo "... src/scripting/LystrParser.i"
	@echo "... src/scripting/LystrParser.s"
	@echo "... src/sync/SynchronizationManager.o"
	@echo "... src/sync/SynchronizationManager.i"
	@echo "... src/sync/SynchronizationManager.s"
	@echo "... src/utils/ErrorHandler.o"
	@echo "... src/utils/ErrorHandler.i"
	@echo "... src/utils/ErrorHandler.s"
	@echo "... src/utils/FileUtils.o"
	@echo "... src/utils/FileUtils.i"
	@echo "... src/utils/FileUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

