name: Build Lyricstator (PC - Linux & Windows)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # Linux dependencies
      # -------------------------------
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git g++ pkg-config \
            libsdl2-dev libvorbis-dev libogg-dev libflac-dev libmpg123-dev \
            libopus-dev libopusfile-dev libxmp-dev libmodplug-dev \
            libfluidsynth-dev libmad0-dev libmikmod-dev libwavpack-dev \
            libsndfile1-dev libfreetype-dev libjpeg-dev libpng-dev libtiff-dev \
            libwebp-dev zlib1g-dev mingw-w64 libfluidsynth2 libfluidsynth-dev

      # -------------------------------
      # Windows dependencies
      # -------------------------------
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install git --yes
          choco install mingw --yes

      # -------------------------------
      # Configure & build
      # -------------------------------
      - name: Configure & build
        run: |
          mkdir -p build && cd build
          cmake .. -DBUILD_SHARED_LIBS=OFF -DSDL_SHARED=OFF -DSDL_STATIC=ON
          cmake --build . --config Release -- -j$(nproc)

      # -------------------------------
      # Upload artifacts
      # -------------------------------
