name: Build Lyricstator (PC - Linux & Windows)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # Linux: build FluidSynth from source
      # -------------------------------
      - name: Build FluidSynth (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git g++ pkg-config \
            libglib2.0-dev libsndfile1-dev libasound2-dev libjack-jackd2-dev \
            libpulse-dev
          
          git clone https://github.com/FluidSynth/fluidsynth.git
          cd fluidsynth
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -Denable-portaudio=OFF -Denable-dbus=OFF
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      # -------------------------------
      # Windows: install with vcpkg
      # -------------------------------
      - name: Install vcpkg and dependencies
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install sdl2 sdl2-mixer[fluidsynth] sdl2-image sdl2-ttf `
              freetype libpng libjpeg-turbo tgui sfml jsoncpp
          echo "VCPKG_ROOT=$PWD" >> $env:GITHUB_ENV

      # -------------------------------
      # Configure & build project
      # -------------------------------
      - name: Configure & build
        run: |
          mkdir -p build && cd build
          if [ "${{ runner.os }}" = "Linux" ]; then
            cmake .. -DBUILD_SHARED_LIBS=OFF -DSDL_SHARED=OFF -DSDL_STATIC=ON
            cmake --build . -- -j$(nproc)
          else
            cmake .. -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake `
                     -DBUILD_SHARED_LIBS=OFF -DSDL_SHARED=OFF -DSDL_STATIC=ON
            cmake --build . --config Release -- /m
          fi

      # -------------------------------
      # Upload artifacts
      # -------------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lyricstator-${{ matrix.os }}
          path: build/
